# Generated by Django 5.0 on 2024-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_model',
            name='photos',
            field=models.ImageField(default=2, upload_to='hotel/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_model',
            name='photos',
            field=models.ImageField(default=3, upload_to='room/images'),
            preserve_default=False,
        ),
    ]
